### ISSUE TITLE
Building on Issue #11

### ISSUE THREAD

**Issue by JamesVo1** [soft-eng-practicum/ForkKnightGame#18]
Perry can push enemies, but enemies can push Perry!

reproduce: let 1 side have more monsters than the other. Notice that they push perry to the opposite side.

Fix: a "response" to being hit. I don't think turning off invulnerability will stop it, since they can continue to push and then provide constant dmg until an animation attack is implemented

**Comment by lyche9** [comment]
This is because the GameObjects being referenced have physics Components. (Perry has mass 2 and zombies have mass 1, thus it takes more zombies to move perry than perry's to move zombie.) 

There are currently at least three open issues ( #9 #11 and #18 ) that essentially stem from the same missing script: how Perry responds when his hitbox collides with an enemy/anything. This WILL (obviously) be implemented eventually.

Is there a way to combine these issues?

**Comment by cengique** [comment]
About combining issues, I think once you refer one from another, they become linked anyway. So when you're ready to close one, you should look at other linked ones to see if you can close them.

I'm impressed with your effort on this project. Keep up the great work!

**Comment by lyche9** [comment]
Fixed: Health system implemented. Perry takes dmg from this now and it can't happen infinitely.
