### ISSUE TITLE
Perry Invincibility Part 2

### ISSUE THREAD

**Issue by JamesVo1** [soft-eng-practicum/ForkKnightGame#9]
Since we want to implement an attack animation, we have to think about a way to implement how Perry's jump will affect gameplay.

I noticed that I can stand on a big zombie, and if are focusing on attacking animations, theres no way he would be hurt if he stays there.

Issue: Sitting on enemy can cause issues

Fix: Maybe create a hitbox on top of a zombie so that if he lands on their head, he also takes damage, otherwise he needs to be "hit" by the zombie

**Comment by lyche9** [comment]
The fix is basically what will happen. See the London tower defense unity game tutorial and how the player takes damage there.

**Comment by JamesVo1** [comment]
yea, but if we create the hitbox on top, do we make him take dmg constantly until he falls off, or does he auto bounce off (referred to in another "bug")

**Comment by lyche9** [comment]
You can reference bugs with the hash symbol followed by the number ID of the bug :)

As mentioned in #2, both the zombie and Perry have hitboxes already, it's just there is no script to handle what happens when Perry's hitbox collides with an enemy. (I think what's confusing here is that the pitchfork is NOT part of Perry's sprite and has its own hitboxe(s)), but it's a child GameObject of Perry's so it follows him around when he moves.) 

What specific event we want to make happen when Perry collides with an enemy hitbox can be up for discussion though. But as for 

> yea, but if we create the hitbox on top

there's already a hitbox that covers that area :)

**Comment by lyche9** [comment]
Jump disabled.
